services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    environment:
      - ESP_HOST=${ESP_HOST:-192.168.0.121}
      - ESP_PORT=${ESP_PORT:-8888}
      - DB_STORAGE=/app/data/data.sqlite
    volumes:
      - ./data:/app/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    ports:
      - "3637:80"
    depends_on:
      - backend
